/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Postinho.gui;

import ConexaoBD.Conexao;
import Postinho.DAO.PacientesDAO;
import Postinho.DTO.PacientesDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emellyv
 */
public class TelaPacientes extends javax.swing.JFrame {


/**
     * Creates new form Pacientes
     */
    public TelaPacientes() {
    initComponents();
    try {
        Connection conexao = new Conexao().getConnection(); // Obtendo conexão
        new PacientesDAO(conexao); // Passando a conexão para o DAO
        listarPacientes(); // Chamando o método para listar os pacientes
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHorarioDeAtendimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSUS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        CadastrarButton = new javax.swing.JButton();
        AtualizarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        CarregarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 51, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        jLabel1.setText("Pacientes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Horario de Atendimento");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("SUS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Telefone");

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacientes.setModel(new DefaultTableModel(     new Object[][]{},      new String[]{"Nome", "CPF", "horarioAtendimento", "Telefone"} ));
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        AtualizarButton.setText("Atualizar");
        AtualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        CarregarButton.setText("Carregar Campos");
        CarregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHorarioDeAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addGap(390, 390, 390))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSUS)
                                    .addComponent(txtTelefone)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CadastrarButton)
                                .addGap(18, 18, 18)
                                .addComponent(AtualizarButton)
                                .addGap(29, 29, 29)
                                .addComponent(ExcluirButton)
                                .addGap(18, 18, 18)
                                .addComponent(CarregarButton))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHorarioDeAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone)
                    .addComponent(jLabel6))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarButton)
                    .addComponent(AtualizarButton)
                    .addComponent(ExcluirButton)
                    .addComponent(CarregarButton))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarButtonActionPerformed
      try {
          atualizarPaciente();
      } catch (SQLException ex) {
          Logger.getLogger(TelaPacientes.class.getName()).log(Level.SEVERE, null, ex);
      }
        listarPacientes();
        limparCamposPacientes();
    }//GEN-LAST:event_AtualizarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed

        excluirPacientes();
        listarPacientes();
        limparCamposPacientes();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void CarregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarButtonActionPerformed
        carregarCampos();
    }//GEN-LAST:event_CarregarButtonActionPerformed

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        cadastrarPaciente();
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
          int selectedRow = tblPacientes.getSelectedRow();
    System.out.println("📌 Linha clicada: " + selectedRow);

    }//GEN-LAST:event_tblPacientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarButton;
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JButton CarregarButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtHorarioDeAtendimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSUS;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
private void cadastrarPaciente() {
    // Capturando os dados do textField
    String nome = txtNome.getText();
    String SUS = txtSUS.getText().trim();
    String telefone = txtTelefone.getText().trim();
    String horarioAtendimento = txtHorarioDeAtendimento.getText().trim();

    if (SUS.isEmpty() || telefone.isEmpty() || nome.isEmpty()) {
        JOptionPane.showMessageDialog(null, "❌ Preencha todos os campos obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Criando o objeto Paciente DTO
        PacientesDTO novoPaciente = new PacientesDTO(nome, SUS, horarioAtendimento, telefone);
        
        System.out.println("Dados capturados do formulario: " + novoPaciente.toString());

        // Query SQL para inserir o Paciente
        String query = "INSERT INTO paciente (nome, SUS, telefone, horarioAtendimento) VALUES (?, ?, ?, ?)";

        // Executa o comando SQL usando o método da classe Conexao
        boolean sucesso = Conexao.executarComandoSQL(query, nome, SUS, telefone, horarioAtendimento);

        if (sucesso) {
            JOptionPane.showMessageDialog(null, "Paciente cadastrado com sucesso.");
            listarPacientes(); // Atualiza a tabela
            limparCamposPaciente();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Paciente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar paciente: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void atualizarPaciente() throws SQLException {
    int selectedRow = tblPacientes.getSelectedRow(); // 🔹 Obtém a linha selecionada
    System.out.println("📌 Tentando atualizar... Linha selecionada: " + selectedRow);

    if (selectedRow == -1) {  // Se nenhuma linha estiver selecionada, exibe erro
        JOptionPane.showMessageDialog(null, "❌ Nenhum cliente foi selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém o SUS do paciente selecionado
    String SUSPacienteSelecionado = (String) tblPacientes.getValueAt(selectedRow, 1); // Coluna 1 = CPF
    System.out.println("📌 SUS do paciente selecionado: " + SUSPacienteSelecionado);

    if (SUSPacienteSelecionado.isEmpty()) {
        JOptionPane.showMessageDialog(null, "SUS do paciente inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém os dados dos campos
    String nome = txtNome.getText();
    String SUS  = txtSUS.getText();
    String telefone = txtTelefone.getText();
    String horarioAtendimento = txtHorarioDeAtendimento.getText();

    if (nome.isEmpty() || SUS.isEmpty() || telefone.isEmpty() || horarioAtendimento.isEmpty()) {
        JOptionPane.showMessageDialog(null, "❌ Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // SQL para atualizar o Paciente
    String query = "UPDATE pacientes SET nome = ?, SUS = ?, telefone = ?, horarioAtendimento = ? WHERE SUS = ?";


    boolean sucesso = Conexao.executarComandoSQL(query, nome, SUS, telefone, horarioAtendimento, SUSPacienteSelecionado);

    if (sucesso) {
        JOptionPane.showMessageDialog(null, "✅ Paciente atualizado com sucesso.");
        listarPacientes();  // Atualiza a tabela
    } else {
        JOptionPane.showMessageDialog(null, "❌ Erro ao atualizar o paciente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void excluirPacientes() {
    int selectedRow = tblPacientes.getSelectedRow(); // Obtém a linha selecionada

    if (selectedRow == -1) {  // Verifica se um paciente foi selecionado
        JOptionPane.showMessageDialog(null, "Selecione um paciente para excluir.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém o Sus do paciente selecionado
    String SUSPacientesSelecionado = (String) tblPacientes.getValueAt(selectedRow, 1); // Coluna 1 = SUS
    System.out.println("SUS do pacientes a excluir: " + SUSPacientesSelecionado);  // 🔥 Debug

    String query = "DELETE FROM pacientes WHERE SUS = ?";

    // Chama o método do ConexaoDAO para executar a exclusão
    boolean sucesso = Conexao.executarComandoSQL(query, SUSPacientesSelecionado);

    if (sucesso) {
        JOptionPane.showMessageDialog(null, "Paciente excluído com sucesso.");
        listarPacientes();  // Atualiza a lista de paciente
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao excluir o paciente.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

private void listarPacientes() {
    try {
        String query = "SELECT * FROM pacientes";
        
        // Usando a classe Conexao para obter a conexão
        try (Connection conn = new Conexao().getConnection(); // Obtém a conexão
             PreparedStatement pst = conn.prepareStatement(query);
             ResultSet rs = pst.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) tblPacientes.getModel();
            model.setNumRows(0); // Limpa a tabela antes de adicionar novos dados

            while (rs.next()) {
                Object[] rowData = {
                    rs.getString("nome"),
                    rs.getString("SUS"),
                    rs.getString("horarioAtendimento"),
                    rs.getString("telefone"),
                };
                model.addRow(rowData);
            }
            tblPacientes.repaint(); // Atualiza a tabela
            tblPacientes.revalidate();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao carregar os pacientes: " + e.getMessage());
    }
}

private void carregarCampos() {
    int selectedRow = tblPacientes.getSelectedRow();
    if (selectedRow != -1) {
        txtNome.setText(tblPacientes.getValueAt(selectedRow, 0).toString());
        txtSUS.setText(tblPacientes.getValueAt(selectedRow, 1).toString());
        txtHorarioDeAtendimento.setText(tblPacientes.getValueAt(selectedRow, 2).toString());
        txtTelefone.setText(tblPacientes.getValueAt(selectedRow, 3).toString());
        
        
    } else {
        System.out.println("Nenhum pacientes selecionado.");
    }
}

private void limparCamposPacientes() {
    txtNome.setText(null);
    txtSUS.setText(null);
    txtHorarioDeAtendimento.setText(null);
    txtTelefone.setText(null);
    txtNome.requestFocus();  
} 

    private void limparCamposPaciente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

private void excluirPaciente() {
    int selectedRow = tblPacientes.getSelectedRow(); // Obtém a linha selecionada na tabela

    if (selectedRow == -1) { // Verifica se uma linha foi selecionada
        JOptionPane.showMessageDialog(null, "❌ Nenhum paciente foi selecionado!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Obtém o SUS do paciente selecionado (assumindo que o SUS está na segunda coluna)
    String SUSPacienteSelecionado = (String) tblPacientes.getValueAt(selectedRow, 1);

    // Confirmação antes de excluir
    int confirmacao = JOptionPane.showConfirmDialog(
        null,
        "Tem certeza que deseja excluir o cliente com SUS " + SUSPacienteSelecionado + "?",
        "Confirmar Exclusão",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacao == JOptionPane.YES_OPTION) {
        try {
            // Query SQL para excluir o paciente
            String query = "DELETE FROM Paciente WHERE SUS = ?";

            // Executa o comando SQL usando a classe Conexao
            boolean sucesso = Conexao.executarComandoSQL(query, SUSPacienteSelecionado);

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "✅ Paciente excluído com sucesso.");
                listarPacientes(); // Atualiza a tabela após a exclusão
            } else {
                JOptionPane.showMessageDialog(null, "❌ Erro ao excluir o paciente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir o paciente: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
} }